//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMWPEntities : DbContext
    {
        public AMWPEntities()
            : base("name=AMWPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Cash> Cash { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<Daily> Daily { get; set; }
        public virtual DbSet<Managements> Managements { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Monthly> Monthly { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<SecOrders> SecOrders { get; set; }
        public virtual DbSet<SecTypes> SecTypes { get; set; }
        public virtual DbSet<Securities> Securities { get; set; }
        public virtual DbSet<Weekly> Weekly { get; set; }
    }
}
