//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Cash
    {
        public long SSN { get; set; }

        [DisplayName("會員代碼")]
        public int MemID { get; set; }

        [DisplayName("現金幣別")]
        [Required(ErrorMessage = "請輸入幣別")]
        public string CCYID { get; set; }

        [DisplayName("金額")]
        [Required(ErrorMessage = "請輸入金額")]
        [Range(0, float.MaxValue, ErrorMessage = "金額不可小於0")]
        public decimal Amount { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Members Members { get; set; }
    }
}
