//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Countries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Countries()
        {
            this.Securities = new HashSet<Securities>();
        }

        [DisplayName("國家代碼")]
        [RegularExpression("[0-9]{2}", ErrorMessage = "格式錯誤，請輸入2碼數字")]
        [Required(ErrorMessage = "請輸入國家代碼")]
        [StringLength(2, ErrorMessage = "國家名稱不可超過2個數字")]
        public string CountryID { get; set; }

        [DisplayName("國家名稱")]
        [Required(ErrorMessage = "請輸入國家名稱")]
        [StringLength(20, ErrorMessage = "國家名稱不可超過20個字")]
        public string Name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Securities> Securities { get; set; }
    }
}
