//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Currencies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currencies()
        {
            this.Cash = new HashSet<Cash>();
            this.Properties = new HashSet<Properties>();
            this.Securities = new HashSet<Securities>();
        }

        [DisplayName("貨幣代碼")]
        [Required(ErrorMessage = "請輸入貨幣代碼")]
        [RegularExpression("[A-Z]{3}", ErrorMessage = "代碼格式錯誤")]
        public string CCYID { get; set; }

        [DisplayName("貨幣名稱")]
        [Required(ErrorMessage = "請輸入貨幣名稱")]
        [StringLength(20, ErrorMessage = "貨幣名稱不可超過20個字")]
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cash> Cash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Properties> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Securities> Securities { get; set; }
    }
}
