//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Properties
    {
        public int SSN { get; set; }

        [DisplayName("會員代碼")]
        public int MemID { get; set; }

        [DisplayName("房產名稱與描述")]
        [StringLength(50, ErrorMessage = "名稱與描述不可超過50個字")]
        [Required(ErrorMessage = "請填寫房產名稱與描述")]
        public string Name { get; set; }

        [DisplayName("房產現價預估值")]
        [Required(ErrorMessage = "請填寫房產現價預估值")]
        [Range(0, double.MaxValue, ErrorMessage = "金額不可小於0")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]

        public double Price { get; set; }

        [DisplayName("貸款日期")]
        [Required(ErrorMessage = "請填寫貸款日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date, ErrorMessage = "日期格式錯誤")]
        public System.DateTime Date { get; set; }

        [DisplayName("貸款金額")]
        [Required(ErrorMessage = "請填寫貸款金額")]
        [Range(0, double.MaxValue, ErrorMessage = "金額不可小於0")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public double Loan { get; set; }

        [DisplayName("貸款期數(月)")]
        [Required(ErrorMessage = "請填寫貸款期數")]
        [Range(0, short.MaxValue, ErrorMessage = "期數不可小於0")]
        public short Term { get; set; }

        [DisplayName("每月還本金額")]
        [Required(ErrorMessage = "請填寫每月還款本金")]
        [Range(0, double.MaxValue, ErrorMessage = "金額不可小於0")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public double Principal { get; set; }

        [DisplayName("每月還款日")]
        [Required(ErrorMessage = "請填寫每月還款日")]
        [Range(1, 31, ErrorMessage = "還款日需介於1-31")]
        public short PayDay { get; set; }

        [DisplayName("貸款幣別")]
        [Required(ErrorMessage = "請填寫貸款幣別")]
        public string CCYID { get; set; }

        public virtual Currencies Currencies { get; set; }
        public virtual Members Members { get; set; }
    }
}
