//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecOrders
    {
        public long SSN { get; set; }
        public int MemID { get; set; }
        public string SecID { get; set; }
        public bool TrancType { get; set; }
        public System.DateTime Date { get; set; }
        public double Share { get; set; }
        public decimal Price { get; set; }
        public decimal Fee { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Securities Securities { get; set; }
    }
}
